### ISSUE TITLE
FileNotFoundError on Windows running genpdf.py

### ISSUE THREAD

**Issue by jtara1** [aviaryan/learnxinyminutes-pdf#7]
OS: Win10
Python 3.6
```
James@j-desktop MINGW64 ~/Temp/learnxinyminutes-pdf (master)
$ python genpdf.py
Traceback (most recent call last):
  File "genpdf.py", line 80, in <module>
    '--latex-engine=xelatex',
  File "C:\Python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I might be missing latex.

**Comment by nbehrnd** [comment]
XeLaTeX isn't a library provided by Python, but one of the TeX engines around (e.g., [Wikipedia's article](https://en.wikipedia.org/wiki/XeTeX) about this topic, its [project page](https://tug.org/xetex/)). Though XeTeX/XeLaTeX are included in [TeX live](https://en.wikipedia.org/wiki/TeX_Live), given you mention Windows as the operating system accessible to you, it should equally be available in the smaller [proTeXt](https://www.tug.org/protext/) / [MikTeX](https://miktex.org/packages/xetex) (sub sets of TeX Live) which specifically address users of Windows.
